version: '3'
services:
  app-server-1:
    build:
      context: ./app-server-1
      dockerfile: Dockerfile
    container_name: app-server-1
    ports:
      - 8000:8000
    networks:
      - nginx-balancer

  app-server-2:
    build:
      context: ./app-server-2
      dockerfile: Dockerfile
    container_name: app-server-2
    ports:
      - 8001:8001
    networks:
      - nginx-balancer

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app-server-1
      - app-server-2
    networks:
      - nginx-balancer

networks:
  nginx-balancer:
    driver: bridge