version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend1
      - backend2


  backend1:
    build:
      context: ./api_1
      dockerfile: Dockerfile
    container_name: backend1
    expose:
      - "8000"

  backend2:
    build:
      context: ./api_2
      dockerfile: Dockerfile
    container_name: backend2
    expose:
      - "8001"