version: '3'
services:
  app-server-1:
    build:
      context: ./app-server-1
      dockerfile: Dockerfile
    container_name: app-server-1
    ports:
      - "8001:8000"
    networks:
      - loadbalancer

  app-server-2:
    build:
      context: ./app-server-2
      dockerfile: Dockerfile
    container_name: app-server-2
    ports:
      - "8002:8000"
    networks:
      - loadbalancer

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-server-1
      - app-server-2
    networks:
      - loadbalancer

networks:
  loadbalancer:
    driver: bridge